---
title: "Biological ontologies and machine learning (scratch)"
author: Correspondence - t.konopka@qmul.ac.uk
output:
  pdf_document:
    keep_tex: true
header-includes:
  \usepackage{caption}
  \usepackage{float}
  \usepackage{amsmath}
  \usepackage{graphicx}
  \usepackage[ruled]{algorithm2e}
  \floatplacement{figure}{H}
  \captionsetup[figure]{labelfont={bf}, name={Figure}, labelsep=period}
---


```{r, analysis.configuration, echo=FALSE}
source("config.R")
source("OML_wrappers.R")
set.seed(1234)
```

```{r, ontologies, echo=FALSE}
source("OML_overview.R")
source("OML_search.R")
source("OML_glm.R")
source("OML_graph.R")
source("OML_casestudies.R")
```

\setcounter{table}{0}
\renewcommand{\thetable}{S\arabic{table}}
\setcounter{figure}{0}
\renewcommand{\thefigure}{S\arabic{figure}}

```{r supfig.ontologies.data, eval=TRUE, echo=FALSE}
supfig.selected = field.widestats[id %in% ontologies.selected]
supfig.selected$filter = ""
.n = nrow(supfig.selected)
supfig.not.selected = field.widestats[!id %in% ontologies.selected]
supfig.not.selected$filter = ""
supfig.not.selected[!id %in% ontologies.recent, "filter"] = "A"
supfig.not.selected[count_zero_depth>10, "filter"] = "G"
supfig.not.selected[!id %in% ontologies.recent & count_zero_depth, "filter"] = "A G"
supfig.not.selected[num_terms<10, "filter"] = "S"
supfig.not.selected.1 = supfig.not.selected[seq_len(.n)]
supfig.not.selected.2 = supfig.not.selected[seq(.n+1, nrow(supfig.not.selected))]
supfig.item.height = 0.08;
supfig.heights = 0.45 + supfig.item.height*c(.n, .n, nrow(supfig.not.selected.2))
```



```{r fig.reconstruction.vertical, eval=FALSE, echo=FALSE, fig.width=3.9, fig.height=supfig.heights[1], fig.cap="\\textbf{Reconstruction of ontologies hierarchy.} Breakdown for self-detection and parent-detection precision for individual ontologies. "}
layout(matrix(c(1,2,3,4), ncol=4, nrow=1, byrow=T),
	   widths=c(0.9, 1.0, 1.0, 1.0))
perf.data = search.performance.summary.wide
perf.model.data = perf.data[obotype=="plain" & datatype=="parents"]
perf.model.data$avg_chars_def = 1+perf.model.data$avg_chars_def
perf.model.data$avg_chars_comments = 1+perf.model.data$avg_chars_comments
plot.bars.group(perf.model.data, var="id", type="label-right")
plot.bars.group(perf.model.data, var="num_terms", type="bars",
				log="x", xlim=c(10, 3000000),
				at=c(10^seq(1:6)),
				at.label=c("", "100", "", "10K", "", "1M"),
				xlab="Size (num. terms)")
plot.bars.group(perf.model.data, var="precision_self", type="bars",
				log="", xlim=c(0, 1),
				at=seq(0, 1, by=0.5),
				xlab="self precision")
plot.bars.group(perf.model.data, var="precision_any_parent", type="bars",
				log="", xlim=c(0, 1),
				at=seq(0, 1, by=0.5),
				xlab="parent precision")
```


\clearpage

**Model with three variables**

\footnotesize

```{r, fig.perf.model, echo=FALSE, eval=TRUE}
perf.model.3 = glm(precision_any_parent ~ log(num_terms) + avg_num_parents + log(avg_chars_text),
				   data=perf.model.data, family="gaussian")
summary(perf.model.3)
```

\normalsize

**Model with four variables**

\footnotesize

```{r, perf.model.4, echo=FALSE, eval=TRUE}
perf.model.4 = glm(precision_any_parent ~ log(num_terms) + avg_num_parents +
		log(avg_chars_def) + log(avg_chars_comments),
				   data=perf.model.data, family="gaussian")
summary(perf.model.4)
```

\normalsize




\clearpage

```{r fig.explaining.plain, eval=FALSE, echo=FALSE, fig.width=6.5, fig.height=3.24, fig.cap="\\textbf{Factors affecting empirical ontology reconstruction based on text descriptions.} Analogous to main figure, here using self-retrieval and parent-retrieval precision from models trained with plain data and queried with plain data (as opposed to parents data in the main figure). "}
layout(matrix(c(1, 2, 3, 4, 5,
				6, 7, 8, 9, 10),
			  ncol=5, nrow=2, byrow=T),
	   widths=c(1.62, 1.22, 1.22, 1.22, 1.22), height=c(1.62, 1.62))
#
plain.model.data = perf.data[obotype=="plain" & datatype=="plain"]
plain.model.data$avg_chars_def = 1+plain.model.data$avg_chars_def
plain.model.data$avg_chars_comments = 1+plain.model.data$avg_chars_comments
fig.explaining(plain.model.data, "precision_self",
			   ylab="self retrieval, precision",
			   panel.label=panel.labels[1],
			   label.ids=list("_", "_", "_", "fbdv", "fbdv"))
fig.explaining(plain.model.data, "precision_any_parent",
			   ylab="parent retrieval, precision",
			   panel.label=panel.labels[2],
			   label.ids=list("_", "_", "_", "fbdv", "fbdv"))
```


```{r fig.explaining.name, eval=FALSE, echo=FALSE, fig.width=6.5, fig.height=3.24, fig.cap="\\textbf{Factors affecting empirical ontology reconstruction based on text descriptions.} Analogous to main figure, here using self-retrieval and parent-retrieval precision from models trained with plain data and queried with name data (as opposed to parents data in the main figure). "}
layout(matrix(c(1, 2, 3, 4, 5,
				6, 7, 8, 9, 10),
			  ncol=5, nrow=2, byrow=T),
	   widths=c(1.62, 1.22, 1.22, 1.22, 1.22), height=c(1.62, 1.62))
#
name.model.data = perf.data[obotype=="plain" & datatype=="name"]
name.model.data$avg_chars_def = 1+plain.model.data$avg_chars_def
name.model.data$avg_chars_comments = 1+plain.model.data$avg_chars_comments
fig.explaining(name.model.data, "precision_self",
			   ylab="self retrieval, precision",
			   panel.label=panel.labels[1],
			   label.ids=list("_", "_", "_", "fbdv", "fbdv"))
fig.explaining(name.model.data, "precision_any_parent",
			   ylab="parent retrieval, precision",
			   panel.label=panel.labels[2],
			   label.ids=list("_", "_", "_", "fbdv", "fbdv"))
```



```{r supfig.glm, eval=TRUE, echo=FALSE, fig.width=3.2, fig.height=supfig.heights[1], fig.cap="\\textbf{Modeling precision for self-retrieval and parent-retrieval.} ."}
layout(matrix(1, nrow=1, ncol=1, byrow=T), widths=c(1, 1))
#
# panel with parent-retrieval
.glm.parent = ontologies.glm.summary[outcome=="precision_any_parent" &
		obotype=="plain" & datatype=="plain"]
.glm.parent = as.data.frame(dcast(variable~oboname, data=.glm.parent, value.var="z value"))
rownames(.glm.parent) = .glm.parent$variable
.glm.parent$variable = NULL
plot.heatmap(abs(.glm.parent[, ontologies.selected]),
			 color.max=20, main="glm modeling of parent-retrieval",
			 legend.main="|z| score",
			 Rcssclass="glm")
```
