name: crossmap-obo-OBONAME-TYPE
comment: OBONAME ontology, entries with TYPE data
data:
  targets: OBONAME-TYPE.yaml.gz
tokens:
  k: 6
features:
  data:
    documents: AUXFILE
  max_number: 1000000
  weighting: [0, 1]
diffusion:
  threshold: 0.05
logging:
  progress: 500000
cache:
  counts: 250000
  data: 250000

